### PR TITLE
feat(outside-org): Create standards around outside org contributions

### LINKED ISSUE #361: [Feat]: Contributing outside our organization
### Is your feature request related to a problem? Please describe.

We have some projects that require collaboration outside of our organization. 

### Describe the solution you'd like.

We have some pre-made docs here: https://github.com/Shift3/ifg/blob/develop/COLLABORATION.md that is used for this. We should add these docs to the standards and practices and make them easier for everyone involved (clients or otherwise).

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by michaelachrisco**
## Changes
1. Add outside org contributions doc to the S&P repo. 

## Purpose
To provide guidance on what to do with a client forked repo based off collaboration and contributions of multiple teams.

## Approach
Create a guide based on previous work. 

I would heavily recommend for anyone looking at this PR to make sure the workflow works. 

Closes #361

### CODE REVIEW

**Comment by michaelachrisco** [comment]
Ill need to pull in the images somewhere. Might take some time.

**Comment by michaelachrisco** [comment]
No idea why awesome_bot is complaining about https://wiki.python.org/moin/BeginnersGuide, it resolves by the look of things. If the reviewers are ok, can you ignore that issue 😄 ill take a closer look some other time (and/or redo the CI job tomorrow).

**Comment by michaelachrisco** [comment]
Anybody have some time on a PR?

**Review by snowhero — APPROVED** [review]
Nicely detailed! I like the workflow of branching out into Bitwise specific sprints. This information will be really beneficial being voiced in a Bitwise Connect for outside organization contributions.

Looks good! Didn't see any typo at the moment on my end.

**Pull request merged**
