### PR TITLE
feature(react-native): Working react native without expo setup

### LINKED ISSUE #94: Circle CI Integration quick-start for various platforms
It would be cool to have a one-stop place for setting up CI with CircleCI for various environments. This includes:

- [x] React Native (with expo)
- [ ] React Native (CRNA)
- [x] Angular

Feel free to add more!

### PR DESCRIPTION
**Pull request by michaelachrisco**
## Changes
1. Add in working version of a react native CircleCI build

## Purpose
We do not currently have a react native build without expo setup and having a working one would help out on future projects. 

# Approach
Use working CircleCI build from another project and add it into our S/P repo.

# Learning

On default, jest is pretty easy to setup initially, but updating it and getting it to work with react native was a challenge. Some of those challenges on the setup side have been documented [here](https://github.com/Shift3/rn-by-example/pull/20). However, the CI portion turned out pretty simple once it was complete. 

Closes #94

### CODE REVIEW

**Review by brandynm34 — COMMENTED** [review]
I know I was tagged in the PR but I've never worked with react native so I cannot efficiently review this PR

**Comment by michaelachrisco** [comment]
> I know I was tagged in the PR but I've never worked with react native so I cannot efficiently review this PR

Solid point, ill do a call out to the react team as well. Either way, let me know if anything stands out or you think needs clarification.

**Comment by michaelachrisco** [comment]
Added react-devs team to the S/P repo.

**Review by JamesVal — COMMENTED** [review]
Seems okay to me but my knowledge of circle CI and docker is a bit lacking at the moment

**Comment by nr431207** [comment]
it looks to be correct, but it's been a long time since I last was exposed to Circle CI.

**Review by nr431207 — COMMENTED** [review]
it looks correct, but it's been a long time since I last was exposed to Circle CI.

**Comment by michaelachrisco** [comment]
@ryekerjh This might be a good topic for a followup on your Github Actions talk? Showing how to use CI and react/react native...Wondering if anyone would be interested or if we have enough projects to validate such a talk?

**Pull request merged**
