### PR TITLE
docs(branch-structure): reasoning behind branch standard

### LINKED ISSUE #157: Add more detail on git branches
As per discussion with @coreyshuman, we should add more detail on why we chose our particular git branching structure. 

When a developer first makes a git branch, the docs state:
> Create feature/fix/task branches to perform your work in. Include your initials so we keep track of who owns branches easily. For example, if I'm (Corey) working on an bug fix task, I'll create a branch such as cts-fix-uploader.

which does not state what modern GUI based git clients (and some command line clients) do with the git branches. Often, these GUI based tools like gitkraken and sourcetree, will organize branches by the standard `<initial>/<issue#>-<short-description>` format and use the <initial> as part of a folder like structure. It makes things much easier to read and followup with a developer on old branches. 

There is also the standard of `<initial>/<feature>/<issue#>-<short-description>` which has the advantage of showing an overarching milestone or feature in the git branch.

We should decide on which branch structure we like to use and then add the reasoning behind it.

### PR DESCRIPTION
**Pull request by michaelachrisco**
## Changes
1. Add more detail to the git branch standard
2. Add reasoning why a developer would want to use the standard.

## Approach
Added more detail to the markdown specifying the exact components or a branch and making it explicit (rather than implicit as the docs were before).

Closes #157

### CODE REVIEW

**Comment by michaelachrisco** [comment]
Question for those reviewing, should we also include the standard `<initial>/<issue#>-<short-description>` or would that be confusing having two possible branch techniques?

**Comment by michaelachrisco** [comment]
@carlosvargas That's a good point. We may not want the prefixed slash because of origin vs remote checkouts. 

To me, as long as the issue number and short description is in the branch, everything should be good for development purposes. The initials are just fine for this org (with this many developers, its a good idea anyways).

**Comment by pratimasakinala** [comment]
That's a good point @carlosvargas. I could get used to using all `-`s. I think we should include the initials so it is easy to reach out to the person working on x issue.

**Comment by michaelachrisco** [comment]
Sounds good to me. @carlosvargas, @mwallert or someone who is a code owner, do we want to merge this one in?

**Comment by mwallert** [comment]
I think it is good to merge but I want to give the others a change to give some input

**Comment by michaelachrisco** [comment]
Fair enough.

**Comment by carlosvargas** [comment]
@ryekerjh @DropsOfSerenity @coreyshuman pinging you guys since our original consensus was having at least 3 code owners approve a standard (should we review that?)

**Comment by michaelachrisco** [comment]
Just let me know if this is good. Ill try to move around some of these pages in other PRs.

**Pull request merged**
