### PR TITLE
docs(standards): fix QA Process link

### LINKED ISSUE #264: Broken Link
## Expected Behavior

When you click on the Link it should re-direct to [https://github.com/Shift3/standards-and-practices/blob/main/standards/qa-process.md](https://github.com/Shift3/standards-and-practices/blob/main/standards/qa-process.md)

## Actual/Current Behavior

When you click the Link it re-directs to [https://github.com/Shift3/standards-and-practices/blob/main/processes/qa-process.md](https://github.com/Shift3/standards-and-practices/blob/main/processes/qa-process.md)

## Steps to Reproduce the Problem

  1. Go to https://github.com/Shift3/standards-and-practices/tree/main/standards#qa-process
  2.  Click QA Process

### PR DESCRIPTION
**Pull request by B12Howard**
## Changes
1. Change broken link for QA Process

## Purpose
QA Process link redirected to 404, did not redirect to readme

## Learning
This was to practice pull requests per the automated onboarding email.

Also, I know we are supposed to merge to the development branch, but this repo doesn't have one (which I think makes sense) so I chose main.

closes #264

### CODE REVIEW

**Review by justincohan — DISMISSED** [review]

**Comment by justincohan** [comment]
It looks like this pr also has a fix.  I think the link in that one might be correct https://github.com/Shift3/standards-and-practices/pull/266

**Review by justincohan — APPROVED** [review]
Nevermind they both link to the same thing

**Comment by coreyshuman** [comment]
@michaelachrisco interesting that awesome_bot didn't catch the broken link. Or is the 404 page actually returned as a user-friendly 200 landing page, which is too complicated for our poor awesome_bot?

**Comment by michaelachrisco** [comment]
> @michaelachrisco interesting that awesome_bot didn't catch the broken link. Or is the 404 page actually returned as a user-friendly 200 landing page, which is too complicated for our poor awesome_bot?

Just threw it into Postman and its returning a 404, so in theory this should work. I _think_ that internal links are whitelisted which might be a bigger issue. We will have to dig a bit.

**Review by michaelachrisco — APPROVED** [review]
Looks good. I think Ill create an issue for awesome_bot for internal links.

**Comment by michaelachrisco** [comment]
Thanks @B12Howard Appreciate you and @JGustavo11 working on this one and quick turnaround :+1:

**Pull request merged**
