### PR TITLE
fix(#368): Fix moves View On Github button below the sidebar nav

### PR DESCRIPTION
**Pull request by markrogers9109**
## Changes

1. Adds custom styles
2. Updates dependencies

## Purpose

The View On Github button was covering the content. [Issue 358](https://github.com/Shift3/standards-and-practices/issues/358)

## Approach

Adds custom CSS to override theme button styles

## Pre-Testing TODOs

- Clone this branch
- Make sure you have Ruby and Jekyll installed
- Run `bundle install`

## Testing Steps

- Run `bundle exec jekyll serve` to host the site locally and view the changes

## Learning

Troubleshoot how the styles are being rendered on the gh-pages site. Find documentation on how to add custom styles to override the leap-day theme. Find out how to test the site locally to verify your changes are working before you push up the changes. Troubleshoot any errors encountered when trying to serve the site locally.

- [How to test your site locally with Jekyll](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll)
- [Review the leap-day theme](https://pages-themes.github.io/leap-day/)

### CODE REVIEW

**Comment by michaelachrisco** [comment]
We have had that issue out for sooo long! Super excited to see what the changes are. 

Is there a url that we can see to test this out? 
A screenshot of the change within the PR description would help others so they dont need to install ruby to review the PR if you dont mind.

**Comment by markrogers9109** [comment]
I don't have a link, but this is an image of what it will look like.
vog-button-new-location

**Comment by michaelachrisco** [comment]
I pulled it down, looks great! Thanks so much for getting that to work. Ill approve and let others review when the get the chance. Awesome job!

**Review by michaelachrisco — APPROVED** [review]
Awesome job!

**Comment by markrogers9109** [comment]
Thanks!

**Review by vagarioustoast — APPROVED** [review]
Looks good to me!

**Pull request merged**
