### PR TITLE
fix(projectBoards): Add new rules per issue #115

### LINKED ISSUE #115: Flesh out Project Boards
We need a more thorough process for _how_ the project boards should be set up, and how to manage the repos for our devs and PMs. 
[Here is the current process](https://github.com/Shift3/standards-and-practices/blob/5757e8e3917f0e3916857017d35cf87e22fc8823/git-and-github/project-setup.md)

@carlosvargas graciously volunteered to head this up [here](https://github.com/Shift3/standards-and-practices/pull/114#pullrequestreview-259025949). Thanks @carlosvargas !! 🤣

### PR DESCRIPTION
**Pull request by ryekerjh**
## Changes
1. Change the documentation for project board setup to match @coreyshuman 's suggestions in issue #115 

## Purpose
Match Shift3's new process

## Approach
Using Github's automation and tooling.

Closes #115

### CODE REVIEW

**Comment by Karvel** [comment]
Do we want to include instructions for how to create the epic project board (the top level project board which shows the progress of each individual board/FS)?

  1. Create a project board.
  2. Create a note (not an issue) for each other project board.
  3. Paste the link to each board in the note.

**Comment by ryekerjh** [comment]
> Do we want to include instructions for how to create the epic project board (the top level project board which shows the progress of each individual board/FS)?
> 
> 1. Create a project board.
> 2. Create a note (not an issue) for each other project board.
> 3. Paste the link to each board in the note.

This sounds good! If you have a spare few minutes can you add this in @Karvel ? If not, I will get to it ASAP

**Comment by Fleury14** [comment]
This may be a silly question, but would it be a good idea to have a sample project board up on this repo to use as kind of a template?

**Comment by ryekerjh** [comment]
> This may be a silly question, but would it be a good idea to have a sample project board up on this repo to use as kind of a template?

🤦‍♂ I thought I had included Sinclair!! I will add this and push it up. Not silly at all, that was the plan!!

**Pull request merged**
