### PR TITLE
feat(react-with-server): Reactjs with server integration

### PR DESCRIPTION
**Pull request by michaelachrisco**
## Changes
1. Add ReactJS and Django server integration within our CI processes.

## Approach
1. Example of both server/client building and testing at the same time in order to move forward with CI process.

References #94

### CODE REVIEW

**Comment by michaelachrisco** [comment]
> I'd love to see some documentation on how to project on both sides (server and client) need to be configured for this to pass. I assume there are specific configurations that need to be done?

Yes, the Django side must have a `test_settings.py` and the react side must have yarn installed. Both are just design decisions that I would love to get feedback on. This is a carbon copy of another project of the Aerostar project.

I can do a quick write-up in a accompanied readme if that would be useful?

I thought I would just drop the PR as a way to get the discussion rolling :P. 
As Linus says, Talk is cheap. Show me the code.

**Comment by ryekerjh** [comment]
> @ryekerjh Yes, the Django side must have a `test_settings.py` and the react side must have `yarn` installed. Both are just design decisions that I would love to get feedback on as far as standards go. This is a carbon copy of the Aerostar projects CI build.
> 
> I can do a quick write-up in a accompanied readme if that would be useful?
> 
> I thought I would just drop the PR as a way to get the discussion rolling :P.
> As Linus says, Talk is cheap. Show me the code.

Ah, Mr. Torvalds...

I think we could just add any specific instructions on the .md file [found here](https://github.com/Shift3/standards-and-practices/blob/master/best-practices/development-tools/continuous-integration/README.md). What do you think? 

As for the newly-age-old debate between NPM and yarn, I don't see much of a difference and we are mostly using NPM (as far as I know) so I'd say stick with that, but that's just my 2 cents.

**Comment by michaelachrisco** [comment]
> > @ryekerjh Yes, the Django side must have a `test_settings.py` and the react side must have `yarn` installed. Both are just design decisions that I would love to get feedback on as far as standards go. This is a carbon copy of the Aerostar projects CI build.
> > I can do a quick write-up in a accompanied readme if that would be useful?
> > I thought I would just drop the PR as a way to get the discussion rolling :P.
> > As Linus says, Talk is cheap. Show me the code.
> 
> Ah, Mr. Torvalds...
> 
> I think we could just add any specific instructions on the .md file [found here](https://github.com/Shift3/standards-and-practices/blob/master/best-practices/development-tools/continuous-integration/README.md). What do you think?

That sounds like a good idea. Might make for a less opinionated setup showing **WHY** we chose the specific setup and focusing more on the fact that you can do two or more CI processes in tandem and show the more common ways of doing said setups.

> 
> As for the newly-age-old debate between NPM and yarn, I don't see much of a difference and we are mostly using NPM (as far as I know) so I'd say stick with that, but that's just my 2 cents.

I'm just glad that both are in a better place honestly. I'm still seeing projects being spun up here with both. Maybe we just include both and let the software developer chose their favorite? Or does someone else have a hard opinion?

**Comment by michaelachrisco** [comment]
> This looks good. I do have a couple of suggestions though:
> 
>     Can we rename the file to `react_with_python_config.yml` since this won't work with a node server? Also, do you know if CircleCI supports "modules" where you could import "build-server"?

Sure, ill have that in a bit.

> Also, do you know if CircleCI supports "modules" where you could import "build-server"?

I am not 100% sure what you are asking about here. Circleci does support building pre-made images (orbs/VMs) that can cache some of the system build/install. Is that what you are referring to?

**Comment by michaelachrisco** [comment]
> @michaelachrisco yeah, from my quick 1 minute glance, I think Orbs are what I meant.
> 
> Basically so that we can reuse the steps to build python/node/react/etc without having to copy and paste the config steps all over the place. You just import those steps into your app config.

Orbs are pretty cool, definitely when you self publish them. We may want to look at the prices of orbs and how many we can have as an org with our current plan.
https://circleci.com/docs/2.0/creating-orbs/

**Pull request merged**
