### PR TITLE
feat(angular-circleci): Angular Circleci build and test

### PR DESCRIPTION
**Pull request by michaelachrisco**
## Changes
1. Add MVP Angular + CircleCI specific yml

## Approach
By adding a known good CircleCI configuration, developers will be able to add CircleCI specific builds and tests to their respective projects. This is the bare minimum to get started. I funny expect this to change in the near future.

## Learning
Learned that Angular now has a direct build page here: https://angular.io/guide/testing#configure-project-for-circle-ci 

References #94

### CODE REVIEW

**Comment by michaelachrisco** [comment]
Also just to make sure this setup works: https://github.com/michaelachrisco/angular-ci-example

I dont have access the circleci on shift3's side but I do have it setup on my own personal account. Working build is here: https://circleci.com/gh/michaelachrisco/angular-ci-example/24?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by carlosvargas** [comment]
@coreyshuman it seems our CircleCI account is out of users. We have the CircleCI 25,000 minutes plan, but not everyone is using because we're out of accounts and we need to upgrade. We have a credit of 88,999 minutes lol

I was looking into Github Actions and since we're a Team Account, we get 15,000 minutes by default. Not sure if you want to take a look and see if we should just move to that (https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions) or figure out if we could add a "Build specific user" to CircleCI to use those credits.

**Comment by michaelachrisco** [comment]
@carlosvargas Thanks!

**Comment by michaelachrisco** [comment]
Very good points @Karvel. Ill take a closer look on Monday and re-edit the config file.

**Comment by michaelachrisco** [comment]
Some changes:
1. Added the official documented angular circleci yml
2. Added the official documented instructions on how to set up your cli. As far as best practices are concerned, we should probably try to always start with the official documentation, and then make custom additions later. I don't think the README is where we want to start getting fancy with our setup, unless we have a very good reason to do so.

**Comment by coreyshuman** [comment]
I'll go ahead and merge this in for now. We can test it out in the boilerplate and expand upon as needed.

**Pull request merged**
