### PR TITLE
added tips for updating servers

### LINKED ISSUE #242: Tips when updating a client server
There is a process our group uses that I believe would be beneficial to document and share. The process is in regards to updating and uploading to client servers. This would ensure less accidental or unwanted files being uploaded.

I want to write out the process on updating and uploading to client servers.

### PR DESCRIPTION
**Pull request by KuanaxBon**
## Changes
1. Added file with tips on when you update a server.

## Purpose
This would help with less accidental or unwanted files being uploaded.

Closes #242

### CODE REVIEW

**Comment by michaelachrisco** [comment]
Thanks for the contribution @KuanaxBon do you mind adding the pr-team to the reviewers?

**Comment by michaelachrisco** [comment]
Ha! Your to quick for me. NVM!

**Comment by michaelachrisco** [comment]
Interesting, the circleci job didn't run here. Im going to have to keep an eye on this branch, thats super strange. 
Ill take a look at the PR separately but I would probably test this out at some point.

**Review by michaelachrisco — COMMENTED** [review]
Thanks for the contribution. We definitely need to expand our docs on server side deploys. 

Couple of suggestions:
1. Do you have any examples of when Pair programming helped with the deploy process? 
2. Im thinking the `--` syntax looks a bit strange here. How do you feel about making the purpose statement its own sub-header (such as `### Purpose`). 
3. I would like there to be more discussion on this topic from other developers before we merge this into the repo. How do you feel about asking for some opinions on the technical discussions slack board?

**Comment by KuanaxBon** [comment]
That sounds great. I'll do some small syntax fixes and add examples of when it helped us. Once i do that, I'll go ahead and start a discussion in the technical discussion slack board.

**Pull request closed without merging**
