### PR TITLE
ar Flywheel Local Processes

### LINKED ISSUE #233: Local by Flywheel Workflow Processes
Certain processes of using flywheel have not been documented. 
Most particularly updating your local database to be current with the dev server. 

This will ensure plugins, pages, copy, and images are consistent amongst all developers. 
This will also ensure that local repos don't get corrupted as this can happen if steps aren't performed in a certain order 

I'd like to write out the process of updating your local database, with steps written in chronological order.

### PR DESCRIPTION
**Pull request by alejandroxsx**
## Changes
1. Add Wordpress directory to SOP
2. Add Instructions on how to update WP Database using Local

## Purpose
To allow developers to update db so WP content is consistent among developers.
Prevent local repo corruption

Closes #233

### CODE REVIEW

**Review by michaelachrisco — CHANGES_REQUESTED** [review]
More information on the Wordpress platform is always welcome. Thanks for the PR!

Can you please put the `Closes #234` within this Pull Request post instead of the title? GitHub has some automation smarts built in, so if you include that line in the body, it will automatically close the Issue once the PR is merged. It will also create a hyperlink reference between the PR and the Issue.

Check out this recent PR for an example: #228

Here's the GitHub documentation on this feature.
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

Before this process becomes a best practice, I would like other Wordpress developers to chime in on the Flywheel process within the issue. Is their any outside links that we can use to give the developer more information on this process?

**Comment by alejandroxsx** [comment]
Thanks for the feedback, changes made. That's a good idea, I have sent the link to this pr to other people in the wp team opening up a dialogue for improvements and other inputs. I noticed that they could't be added as reviewers to this PR and was wondering that was possible?

**Comment by michaelachrisco** [comment]
Thats a good idea, ill add the wordpress team to the repo. Thanks!

**Comment by michaelachrisco** [comment]
@alejandroxsx I added the Wordpress team to the repo to triage some of these Wordpress specific PRs. Github assigned a new developer to take a look at this PR.

**Comment by coreyshuman** [comment]
This is very helpful. At the moment, we have our entire WordPress Developer Process documented in this SOP document here: https://docs.google.com/document/d/1i6NJH5fXt6MHf0aXHeDCzAhUeE0jOiKevmB3Jn_s51s/edit?usp=sharing

While there is a larger discussion to be had about what belongs in a doc versus this repo, for now I would recommend that this content be added to the linked Google Doc instead so as to keep all WP development content in one place.

Also small fix, it should actually be "closes #233"

**Comment by michaelachrisco** [comment]
> This is very helpful. At the moment, we have our entire WordPress Developer Process documented in this SOP document here: https://docs.google.com/document/d/1i6NJH5fXt6MHf0aXHeDCzAhUeE0jOiKevmB3Jn_s51s/edit?usp=sharing
> 
> While there is a larger discussion to be had about what belongs in a doc versus this repo, for now I would recommend that this content be added to the linked Google Doc instead so as to keep all WP development content in one place.
> 
> Also small fix, it should actually be "closes #233"

@coreyshuman How do you feel about us adding the [google doc](https://docs.google.com/document/d/1i6NJH5fXt6MHf0aXHeDCzAhUeE0jOiKevmB3Jn_s51s/edit?usp=sharing) to the wordpress documentation within the S&P repo?

**Comment by alejandroxsx** [comment]
Sounds good I'll add it to the doc, in the meanwhile should I close this pull request?

**Comment by michaelachrisco** [comment]
yep go ahead and close it. Appreciate the work!

**Pull request closed without merging**
