### PR TITLE
feat(nodemailer): best practices for nodemailer

### PR DESCRIPTION
**Pull request by TomAlperin**
1. Sets guidelines for using HTML with Nodemailer.

### CODE REVIEW

**Comment by DropsOfSerenity** [comment]
A few comments:

* CSS Inlining should be automated, and you should be able to write the css non-inlined, this allows for better maintainability and easier changes to email content and styling. There are many packages that handle the css inlining for you. We should probably use one of these as standard. Something similar to https://github.com/fphilipe/premailer-rails would be preferred.
* 👍 on always including a text email, in general email etiquette html is optional, text is not.
* For email that is longer, it's often useful to use a templating engine, like ejs so you can draft the email out in a file, nodemailer has a few useful plugins: https://nodemailer.com/plugins/
* In rails i used to use letter_opener whenever I mail stuff, but https://github.com/niftylettuce/preview-email looks to be the equivalent in node. This will (in development) open your browser window with the email sent so you can easily see what was sent. Something like this should be a standard probably as it eases development a lot.

**Comment by TomAlperin** [comment]
> @TomAlperin can you also add examples of the `.text.pug` file?

I was not sure if this should be included since it is a different library and using Nodemailer does not require using Pug. Should there be further discussion on whether Pug will be required?

**Comment by TomAlperin** [comment]
> @TomAlperin can you also add examples of the `.text.pug` file?

@ryekerjh I was not sure if this should be included since it is a different library and using Nodemailer does not require using Pug. Should there be further discussion on whether Pug will be required?

**Comment by ryekerjh** [comment]
> > @TomAlperin can you also add examples of the `.text.pug` file?
> 
> @ryekerjh I was not sure if this should be included since it is a different library and using Nodemailer does not require using Pug. Should there be further discussion on whether Pug will be required?

I don't think it needs to be required, but we can include it as an example of how we _could_ do this.

**Comment by DropsOfSerenity** [comment]
Recommend something like this: https://github.com/forwardemail/email-templates seems to include all the goodies I would want to see in a complete email templating/inlining development setup

**Comment by mwallert** [comment]
> Recommend something like this: https://github.com/forwardemail/email-templates seems to include all the goodies I would want to see in a complete email templating/inlining development setup

@TomAlperin

**Comment by coreyshuman** [comment]
Email templates are part of the SOW for the boilerplates. Since they will be addressed there, I don't think we need to spend time on it here. I think this looks good as an initial example for nodemailer. Anyone have any other glaring concerns that require blocking this submission?
@DropsOfSerenity @ryekerjh @mwallert @carlosvargas ?

**Comment by mwallert** [comment]
@coreyshuman Sounds good to me

**Pull request merged**
